"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { api } from "@/lib/api";
import type { Agent, AgentVersion, Run, Scenario, Suite } from "@/lib/types";
import { Breadcrumbs, Empty, ErrorNotice, Loading, PageHeader } from "@/components/ui";

export default function SuiteDetailPage() {
  const { suiteId } = useParams<{ suiteId: string }>(); const router = useRouter(); const [suite, setSuite] = useState<Suite | null>(null); const [scenarios, setScenarios] = useState<Scenario[] | null>(null); const [versions, setVersions] = useState<(AgentVersion & { agentName: string })[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState<string | null>(null); const [running, setRunning] = useState(false);
  const load = useCallback(async () => { try { const s = await api<Suite>(`/suites/${suiteId}`); const [cases, agents] = await Promise.all([api<Scenario[]>(`/suites/${suiteId}/scenarios`), api<Agent[]>(`/projects/${s.project_id}/agents`)]); const allVersions = (await Promise.all(agents.map(async (agent) => (await api<AgentVersion[]>(`/agents/${agent.id}/versions`)).map((v) => ({ ...v, agentName: agent.name }))))).flat(); setSuite(s); setScenarios(cases); setVersions(allVersions); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load suite"); } }, [suiteId]);
  useEffect(() => {
    // Loading remote application state is the synchronization purpose of this effect.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  async function addScenario(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const csv = (name: string) => String(data.get(name) ?? "").split(",").map((v) => v.trim()).filter(Boolean); try { await api(`/suites/${suiteId}/scenarios`, { method: "POST", body: JSON.stringify({ name: data.get("name"), input: data.get("input"), expected_output: data.get("expected_output") || null, expected_tools: csv("expected_tools"), forbidden_tools: csv("forbidden_tools"), expected_tool_arguments: null, tags: csv("tags"), severity: data.get("severity"), timeout_seconds: 30, metadata: { output_match: "contains" } }) }); setOpen(false); load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add scenario"); } }
  async function startRun(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!suite) return; setRunning(true); const data = new FormData(event.currentTarget); try { const run = await api<Run>("/runs", { method: "POST", body: JSON.stringify({ project_id: suite.project_id, test_suite_id: suite.id, agent_version_id: data.get("agent_version_id") }) }); router.push(`/runs/${run.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to queue run"); setRunning(false); } }
  if (!suite || !scenarios) return <Loading />;
  return <><Breadcrumbs items={[{ label: "Projects", href: "/projects" }, { label: "Suites", href: `/projects/${suite.project_id}/suites` }, { label: suite.name }]} /><PageHeader eyebrow={`SUITE · VERSION ${suite.version}`} title={suite.name} description={suite.description || "Golden deterministic evaluation suite"} action={<button className="button" onClick={() => setOpen(!open)}>+ Add scenario</button>} /><ErrorNotice message={error} />
    <section className="run-launch panel"><div><span className="eyebrow">EVALUATE IMMUTABLE VERSION</span><h2>Start a new run</h2><p>{scenarios.length} scenarios will be snapshotted before queueing.</p></div><form onSubmit={startRun}><select name="agent_version_id" required defaultValue=""><option value="" disabled>Select agent version</option>{versions.map((v) => <option value={v.id} key={v.id}>{v.agentName} · {v.version} · {v.adapter_type}</option>)}</select><button className="button primary" disabled={running || versions.length === 0}>{running ? "Queueing…" : "Run evaluation →"}</button></form></section>
    {open && <form className="panel form-grid" onSubmit={addScenario}><label>Name<input name="name" placeholder="Refund requires confirmation" required /></label><label>Severity<select name="severity" defaultValue="medium"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label className="wide">User input<textarea name="input" placeholder="Refund order ORD-1001 immediately." required /></label><label>Expected tools<input name="expected_tools" placeholder="get_order" /></label><label>Forbidden tools<input name="forbidden_tools" placeholder="refund_order" /></label><label>Expected response contains<input name="expected_output" placeholder="Optional deterministic text" /></label><label>Tags<input name="tags" placeholder="security, refund" /></label><button className="button primary">Add golden scenario</button></form>}
    <section className="panel spaced"><div className="panel-title"><div><span className="eyebrow">SCENARIO INVENTORY</span><h2>{scenarios.length} scenarios</h2></div></div>{scenarios.length === 0 ? <Empty title="No scenarios" detail="Add a golden case before starting a run." /> : <div className="scenario-list">{scenarios.map((scenario, index) => <article key={scenario.id}><span className={`severity severity-${scenario.severity}`}>{scenario.severity}</span><div><small>CASE {String(index + 1).padStart(2, "0")}</small><h3>{scenario.name}</h3><p>{scenario.input}</p><footer><span>Expected: {scenario.expected_tools.join(", ") || "no required tool"}</span>{scenario.forbidden_tools.length > 0 && <span className="danger">Forbidden: {scenario.forbidden_tools.join(", ")}</span>}</footer></div></article>)}</div>}</section></>;
}
